import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AuthContextProvider from "@/context/authcontext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="pastel">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-theme="pastel"
      >
        <AuthContextProvider>
        {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
